// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: pb/helloWorldPB/hello_world.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 请求参数
type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_pb_helloWorldPB_hello_world_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_helloWorldPB_hello_world_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_pb_helloWorldPB_hello_world_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 响应参数
type HelloReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloReply) Reset() {
	*x = HelloReply{}
	mi := &file_pb_helloWorldPB_hello_world_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_pb_helloWorldPB_hello_world_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_pb_helloWorldPB_hello_world_proto_rawDescGZIP(), []int{1}
}

func (x *HelloReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_pb_helloWorldPB_hello_world_proto protoreflect.FileDescriptor

const file_pb_helloWorldPB_hello_world_proto_rawDesc = "" +
	"\n" +
	"!pb/helloWorldPB/hello_world.proto\x12\fhelloWorldPB\" \n" +
	"\fHelloRequest\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"\x1e\n" +
	"\n" +
	"HelloReply\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg2\x8e\x01\n" +
	"\aGreeter\x12B\n" +
	"\bSayHello\x12\x1a.helloWorldPB.HelloRequest\x1a\x18.helloWorldPB.HelloReply\"\x00\x12?\n" +
	"\x05SayHi\x12\x1a.helloWorldPB.HelloRequest\x1a\x18.helloWorldPB.HelloReply\"\x00B\x04Z\x02./b\x06proto3"

var (
	file_pb_helloWorldPB_hello_world_proto_rawDescOnce sync.Once
	file_pb_helloWorldPB_hello_world_proto_rawDescData []byte
)

func file_pb_helloWorldPB_hello_world_proto_rawDescGZIP() []byte {
	file_pb_helloWorldPB_hello_world_proto_rawDescOnce.Do(func() {
		file_pb_helloWorldPB_hello_world_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_helloWorldPB_hello_world_proto_rawDesc), len(file_pb_helloWorldPB_hello_world_proto_rawDesc)))
	})
	return file_pb_helloWorldPB_hello_world_proto_rawDescData
}

var file_pb_helloWorldPB_hello_world_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_helloWorldPB_hello_world_proto_goTypes = []any{
	(*HelloRequest)(nil), // 0: helloWorldPB.HelloRequest
	(*HelloReply)(nil),   // 1: helloWorldPB.HelloReply
}
var file_pb_helloWorldPB_hello_world_proto_depIdxs = []int32{
	0, // 0: helloWorldPB.Greeter.SayHello:input_type -> helloWorldPB.HelloRequest
	0, // 1: helloWorldPB.Greeter.SayHi:input_type -> helloWorldPB.HelloRequest
	1, // 2: helloWorldPB.Greeter.SayHello:output_type -> helloWorldPB.HelloReply
	1, // 3: helloWorldPB.Greeter.SayHi:output_type -> helloWorldPB.HelloReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_helloWorldPB_hello_world_proto_init() }
func file_pb_helloWorldPB_hello_world_proto_init() {
	if File_pb_helloWorldPB_hello_world_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_helloWorldPB_hello_world_proto_rawDesc), len(file_pb_helloWorldPB_hello_world_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_helloWorldPB_hello_world_proto_goTypes,
		DependencyIndexes: file_pb_helloWorldPB_hello_world_proto_depIdxs,
		MessageInfos:      file_pb_helloWorldPB_hello_world_proto_msgTypes,
	}.Build()
	File_pb_helloWorldPB_hello_world_proto = out.File
	file_pb_helloWorldPB_hello_world_proto_goTypes = nil
	file_pb_helloWorldPB_hello_world_proto_depIdxs = nil
}
