// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: pb/Sample/sample_hello.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SampleHelloService_Hello_FullMethodName = "/SampleHelloPB.SampleHelloService/Hello"
)

// SampleHelloServiceClient is the client API for SampleHelloService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SampleHelloServiceClient interface {
	// 连接到数据库
	Hello(ctx context.Context, in *HelloReq, opts ...grpc.CallOption) (*HelloRsp, error)
}

type sampleHelloServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSampleHelloServiceClient(cc grpc.ClientConnInterface) SampleHelloServiceClient {
	return &sampleHelloServiceClient{cc}
}

func (c *sampleHelloServiceClient) Hello(ctx context.Context, in *HelloReq, opts ...grpc.CallOption) (*HelloRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloRsp)
	err := c.cc.Invoke(ctx, SampleHelloService_Hello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SampleHelloServiceServer is the server API for SampleHelloService service.
// All implementations must embed UnimplementedSampleHelloServiceServer
// for forward compatibility.
type SampleHelloServiceServer interface {
	// 连接到数据库
	Hello(context.Context, *HelloReq) (*HelloRsp, error)
	mustEmbedUnimplementedSampleHelloServiceServer()
}

// UnimplementedSampleHelloServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSampleHelloServiceServer struct{}

func (UnimplementedSampleHelloServiceServer) Hello(context.Context, *HelloReq) (*HelloRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedSampleHelloServiceServer) mustEmbedUnimplementedSampleHelloServiceServer() {}
func (UnimplementedSampleHelloServiceServer) testEmbeddedByValue()                            {}

// UnsafeSampleHelloServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SampleHelloServiceServer will
// result in compilation errors.
type UnsafeSampleHelloServiceServer interface {
	mustEmbedUnimplementedSampleHelloServiceServer()
}

func RegisterSampleHelloServiceServer(s grpc.ServiceRegistrar, srv SampleHelloServiceServer) {
	// If the following call pancis, it indicates UnimplementedSampleHelloServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SampleHelloService_ServiceDesc, srv)
}

func _SampleHelloService_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SampleHelloServiceServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SampleHelloService_Hello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SampleHelloServiceServer).Hello(ctx, req.(*HelloReq))
	}
	return interceptor(ctx, in, info, handler)
}

// SampleHelloService_ServiceDesc is the grpc.ServiceDesc for SampleHelloService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SampleHelloService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SampleHelloPB.SampleHelloService",
	HandlerType: (*SampleHelloServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _SampleHelloService_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/Sample/sample_hello.proto",
}
