// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: pb/Sample/sample_hello.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReqMessage    string                 `protobuf:"bytes,1,opt,name=req_message,json=reqMessage,proto3" json:"req_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloReq) Reset() {
	*x = HelloReq{}
	mi := &file_pb_Sample_sample_hello_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReq) ProtoMessage() {}

func (x *HelloReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_Sample_sample_hello_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReq.ProtoReflect.Descriptor instead.
func (*HelloReq) Descriptor() ([]byte, []int) {
	return file_pb_Sample_sample_hello_proto_rawDescGZIP(), []int{0}
}

func (x *HelloReq) GetReqMessage() string {
	if x != nil {
		return x.ReqMessage
	}
	return ""
}

type HelloRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RspMessage    string                 `protobuf:"bytes,1,opt,name=rsp_message,json=rspMessage,proto3" json:"rsp_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRsp) Reset() {
	*x = HelloRsp{}
	mi := &file_pb_Sample_sample_hello_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRsp) ProtoMessage() {}

func (x *HelloRsp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_Sample_sample_hello_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRsp.ProtoReflect.Descriptor instead.
func (*HelloRsp) Descriptor() ([]byte, []int) {
	return file_pb_Sample_sample_hello_proto_rawDescGZIP(), []int{1}
}

func (x *HelloRsp) GetRspMessage() string {
	if x != nil {
		return x.RspMessage
	}
	return ""
}

var File_pb_Sample_sample_hello_proto protoreflect.FileDescriptor

const file_pb_Sample_sample_hello_proto_rawDesc = "" +
	"\n" +
	"\x1cpb/Sample/sample_hello.proto\x12\rSampleHelloPB\"+\n" +
	"\bHelloReq\x12\x1f\n" +
	"\vreq_message\x18\x01 \x01(\tR\n" +
	"reqMessage\"+\n" +
	"\bHelloRsp\x12\x1f\n" +
	"\vrsp_message\x18\x01 \x01(\tR\n" +
	"rspMessage2O\n" +
	"\x12SampleHelloService\x129\n" +
	"\x05Hello\x12\x17.SampleHelloPB.HelloReq\x1a\x17.SampleHelloPB.HelloRspB\x04Z\x02./b\x06proto3"

var (
	file_pb_Sample_sample_hello_proto_rawDescOnce sync.Once
	file_pb_Sample_sample_hello_proto_rawDescData []byte
)

func file_pb_Sample_sample_hello_proto_rawDescGZIP() []byte {
	file_pb_Sample_sample_hello_proto_rawDescOnce.Do(func() {
		file_pb_Sample_sample_hello_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_Sample_sample_hello_proto_rawDesc), len(file_pb_Sample_sample_hello_proto_rawDesc)))
	})
	return file_pb_Sample_sample_hello_proto_rawDescData
}

var file_pb_Sample_sample_hello_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_Sample_sample_hello_proto_goTypes = []any{
	(*HelloReq)(nil), // 0: SampleHelloPB.HelloReq
	(*HelloRsp)(nil), // 1: SampleHelloPB.HelloRsp
}
var file_pb_Sample_sample_hello_proto_depIdxs = []int32{
	0, // 0: SampleHelloPB.SampleHelloService.Hello:input_type -> SampleHelloPB.HelloReq
	1, // 1: SampleHelloPB.SampleHelloService.Hello:output_type -> SampleHelloPB.HelloRsp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_Sample_sample_hello_proto_init() }
func file_pb_Sample_sample_hello_proto_init() {
	if File_pb_Sample_sample_hello_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_Sample_sample_hello_proto_rawDesc), len(file_pb_Sample_sample_hello_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_Sample_sample_hello_proto_goTypes,
		DependencyIndexes: file_pb_Sample_sample_hello_proto_depIdxs,
		MessageInfos:      file_pb_Sample_sample_hello_proto_msgTypes,
	}.Build()
	File_pb_Sample_sample_hello_proto = out.File
	file_pb_Sample_sample_hello_proto_goTypes = nil
	file_pb_Sample_sample_hello_proto_depIdxs = nil
}
